### ISSUE TITLE
如何在目录中移除摘要和目录的显示

### ISSUE THREAD

**Issue by lukan217** [CamuseCao/XMU-Undergraduate-thesis-template#10]
RT，旧的模板好像加个命令就可以，新版加了命令没有效果，其实我只是感觉英文目录中既有中文又有英文显示很不雅，如果能够全英显示就好了
![image](https://user-images.githubusercontent.com/29795496/114358214-41284780-9ba5-11eb-9757-f59f8e9e0a1c.png)

**Comment by CamuseCao** [comment]
请参考模板使用手册中的 `nottoc, notabs, notbib` 三个选项的说明。
