### ISSUE TITLE
生僻字显示问题

### ISSUE THREAD

**Issue by YingqianChen** [CamuseCao/XMU-Undergraduate-thesis-template#12]
中文生僻字的显示存在一些问题，如图所示，尝试了网上一些解决方法，但还是没有解决。
![image](https://github.com/CamuseCao/XMU-thesis/assets/100850064/7905c528-f503-467e-91e1-930c7a69fee7)

**Comment by CamuseCao** [comment]
根据学校要求的字体设置，字体覆盖面积确实不够广泛，此处可以考虑下载 noto 字体。在命令行输入 `texdoc xecjk` ，查看 xecjk 手册第 7 页的例 5 ，设置 NotoSansCJKsc 中文字体，在此处使用该字体即可。 noto 字体应该能满足需求。

PS: 提问的时候能更详细有助于问题的解决，例如具体是哪个字不显示。 noto 字体比较全，但也可能不够，还可以考虑花园明朝体此类覆盖面积更广的字体。另外，尝试了什么失败了也可以描述一下。
