### ISSUE TITLE
节的字体有误

### ISSUE THREAD

**Issue by HumbleBone** [CamuseCao/XMU-Undergraduate-thesis-template#2]
节的标题和三级标题没有使用黑体 希望可以修正一下

**Comment by HumbleBone** [comment]
希望可以修改一下三级标题的缩进，当前版本的缩进间距太大，如果能够和二级标题的缩进对齐，会美观很多！！

**Comment by CamuseCao** [comment]
感谢你提出的问题，标题字体我已经修正了，是由于某个指令没有到达预期的效果。缩进问题之前版本是没问题的，有一次我自己误修改了，现在改正回来了。现在下载最新的模板使用试试。如果还有别的问题欢迎继续提issue。
