### ISSUE TITLE
[Feature request] 能够增加linux的支持？

### ISSUE THREAD

**Issue by zhuyinheng** [CamuseCao/XMU-Undergraduate-thesis-template#3]
常用的发行版如ubuntu 18.04

**Comment by CamuseCao** [comment]
你好，其实·`Linux`系统支持目前只差是字体问题。这个支持的添加这两天可能没办法弄好。但是我可以给出解决方案。首先得会安装字体，需要思源和文泉驿字体，所选字体均是开源的，并且个人自由使用。具体的所需字体在下面代码里。在settings/setting.tex文件中搜索setCJKmainfont，能找到三行。定位之后替换成如下代码：

```tex
\setCJKmainfont[ItalicFont={Source Han Serif Light}, BoldFont={Source Han Serif Bold}]{Source Han Serif SC}
\setCJKsansfont[ItalicFont={Source Han Sans CN ExtraLight}, BoldFont={Source Han Sans CN Bold Bold}]{Source Han Sans CN Normal}
\setCJKmonofont{WenQuanYi Micro Hei Mono}%等宽字体 文泉驿等宽微米雅黑
```


未来会添加更加友好的接口。这两天大家应该都在赶论文。我只能过段时间再考虑更好的优化了。希望能暂时解决你的需求。

**Comment by zhuyinheng** [comment]
感谢您的回答！
我的问题解决了，这里分享一下解决方案：
1.  sudo apt-get install ttf-mscorefonts-installer #安装ttf-mscorefonts-installer字体包
2. sudo fc-cache -f -v #更新字体缓存
3. 查看已经安装的字体
4. 在如上位置设置字体
确实只是字体的问题感觉问题不大。

**Comment by CamuseCao** [comment]
很感谢你的分享，有兴趣的话你可以提一个pr,等过了我论文的二辩我会考虑再优化这方面的工作。

**Comment by zhuyinheng** [comment]
@CamuseCao 哈哈哈祝答辩顺利

**Comment by CamuseCao** [comment]
`win` 和 `Mac` 都已经能够直接运行了， `Linux` 下的运行要求也已经明确。算完成支持了。
