### ISSUE TITLE
章节标题的格式有误

### ISSUE THREAD

**Issue by zhuyinheng** [CamuseCao/XMU-Undergraduate-thesis-template#5]
突然发现模版中章节标题的格式和本科生论文要求不一样
![image](https://user-images.githubusercontent.com/16465741/58176577-26106e00-7cd5-11e9-8b07-4b7af99111d3.png)
![image](https://user-images.githubusercontent.com/16465741/58176610-39233e00-7cd5-11e9-8795-055d43cc49f9.png)

**Comment by zhuyinheng** [comment]
我自己尝试着更改了一下，但是格式就发生了错乱...

**Comment by CamuseCao** [comment]
虽然学校这么要求了，但是我自己有些不想遵守。但是改的方法是有的，在 `setting.tex` 文件中搜索 `@chaplable[1]` 后面的东西修改一下，然后再改一下距离，搜索 `{\@chaplable{\thechapter}}` 修改后面 `\hspace` 的值调整，页眉格式也要跟着改，再修改 `\fancyhead[CO]`里面把 `\CTEXthechapter\quad` 去掉。祝顺利。

我也觉得我这边写得大家很难读懂，我现在正在重构它，让它更简单易懂，先将就这样用吧。

**Comment by zhuyinheng** [comment]
![image](https://user-images.githubusercontent.com/16465741/58431817-c1408380-80d9-11e9-87fc-3de3a7323acc.png)
还有目录的字体似乎也不太对

**Comment by CamuseCao** [comment]
不好意思，有几天没关注这里的消息了，新版本的目录字体设置应该没问题，如果有不对的你具体指出一下是哪级的有问题，我几乎认不出字体。
