### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by keimmy** [CamuseCao/XMU-Undergraduate-thesis-template#7]
您好！我是之前在邮箱有联系过你的学妹~。我已经将论文写得差不多了，今天在进行参考文献的引用设置。本来都没有什么问题，但是在最后点击运行后出现了这个错误。我没有动过这边的代码，小白看不懂呀，也不敢乱动...package方面我只有添加一些我需要的，没有删减过。

Fatal Package fontspec Error: The fontspec package requires either XeTeX or(fontspec) LuaTeX. \msg_fatal:nn {fontspec} {cannot-use-pdftex}

![1585899576(1)](https://user-images.githubusercontent.com/62934868/78336074-5ac1a700-75c1-11ea-95a4-fc592ac620c7.jpg)

**Comment by CamuseCao** [comment]
这里出错的理由很简单，需要使用 xelatex 来编译，你却使用了 pdflatex
来编译。改变编译方式应该就没问题了。

刚刚把提醒邮件看错了。

keimmy <notifications@github.com> 于2020年4月3日周五 下午3:40写道：
